FROM openresty/openresty:1.15.8.1-alpine

RUN apk update && \
apk --no-cache upgrade && \
mkdir -pv /var/www/cache && \
wget -O - https://github.com/DataDog/dd-opentracing-cpp/releases/download/v0.3.0/linux-amd64-libdd_opentracing_plugin.so.gz | gunzip -c > /usr/local/lib/libdd_opentracing_plugin.so && \
wget "https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.33-r0/glibc-2.33-r0.apk" && \
wget "https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.33-r0/glibc-bin-2.33-r0.apk" && \
apk add --allow-untrusted glibc-2.33-r0.apk glibc-bin-2.33-r0.apk && \
wget https://pkgs.alpinelinux.org/package/edge/main/x86/libbsd-dev && \
wget https://pkgs.alpinelinux.org/package/edge/main/x86/libbsd && \
ln -svf /usr/glibc-compat/lib/ld-linux-x86-64.so.2 /usr/glibc-compat/sbin/ldconfig

ADD nginx.conf /usr/local/openresty/nginx/conf/nginx.conf
ADD dd-config.json /usr/local/openresty/nginx/conf/dd-config.json
RUN ls -lR /usr/local/ && ls -lR /usr/local/openresty/nginx/modules/


# Install nginx-opentracing
RUN get_latest_release() { \
  wget -qO- "https://api.github.com/repos/$1/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'; \
  } && \
  NGINX_VERSION=`nginx -v 2>&1 > /dev/null | sed -E "s/^.*nginx\/(.*)/\\1/"`&& \
  OPENTRACING_NGINX_VERSION="$(get_latest_release opentracing-contrib/nginx-opentracing)" && \
  DD_OPENTRACING_CPP_VERSION="$(get_latest_release DataDog/dd-opentracing-cpp)" && \
  \
  wget https://github.com/opentracing-contrib/nginx-opentracing/releases/download/v0.14.0/linux-amd64-nginx-1.15.8-ot16-ngx_http_module.so.tgz && \
  NGINX_MODULES=$(nginx -V 2>&1 | grep "configure arguments" | sed -n 's/.*--modules-path=\([^ ]*\).*/\1/p') && \
  tar zxvf linux-amd64-nginx-1.15.8-ot16-ngx_http_module.so.tgz -C /usr/local/openresty/nginx/modules/ && \
  # Install Datadog module
  wget -O - https://github.com/DataDog/dd-opentracing-cpp/releases/download/v1.3.0/linux-amd64-libdd_opentracing_plugin.so.gz | gunzip -c > /usr/local/lib/libdd_opentracing_plugin.so