---
- hosts: localhost
  gather_facts: yes
  become: yes
  become_user: root

  vars:
   destination: /home/cloud_user
   version_old: 3.6.0-1
   version_new: 3.8.2-1

  tasks:
    - name: "Download and Extract the Ansible Tower 3.6 Tar Ball"
      unarchive:
        src: "https://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-{{version_old}}.tar.gz"
        dest: "{{ destination }}"
        remote_src: yes
      become_user: root
      tags:
      - upgrade_36

    - name: "Download and Extract the Ansible Tower 3.8 Tar Ball"
      unarchive:
        src: "https://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-{{version_new}}.tar.gz"
        dest: "{{ destination }}"
        remote_src: yes
      become_user: root
      tags:
      - upgrade_38

    - name: "Copy the inventory template"
      copy:
        src: inventory
        dest: "{{ destination }}/ansible-tower-setup-{{version_old}}"
        owner: cloud_user
        group: cloud_user
        mode: 0644
      tags:
      - upgrade_36

    - name: "Copy the inventory template"
      copy:
        src: inventory
        dest: "{{ destination }}/ansible-tower-setup-{{version_new}}"
        owner: cloud_user
        group: cloud_user
        mode: 0644
      tags:
      - upgrade_38

    - name: "Run Ansible tower"
      shell: "sudo ./setup.sh"
      args:
        chdir: "{{ destination }}/ansible-tower-setup-{{version_old}}"
      tags:
      - upgrade_36

    - name: "Run Ansible tower"
      shell: "sudo ./setup.sh"
      args:
        chdir: "{{ destination }}/ansible-tower-setup-{{version_new}}"
      tags:
      - upgrade_38