---
- hosts: localhost
  gather_facts: yes
  become: yes
  become_user: root

  tasks:
    - name: "Downloading Epel release"
      get_url:
        url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        dest: /tmp

    - name: "Installing Epel Release"
      yum:
        name: /tmp/epel-release-latest-7.noarch.rpm
        state: present

    - name: "Upgrade Ansible"
      yum:
        name: ansible

    - name: "Printing the Ansible Version"
      shell: ansible --version
      register: version

    - debug:
        msg: System has Ansible Version {{version.stdout_lines}}

    - name: "Install Ansible Tower"
      get_url:
        url: https://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-latest.tar.gz
        dest: /tmp
      become_user: root

    - name: "Extract the Ansible Tower Tar Ball"
      unarchive:
        src: /tmp/ansible-tower-setup-latest.tar.gz
        dest: /tmp
      become_user: root