---
- hosts: windows
  gather_facts: yes

  tasks:
   - name: "Copy Zabbix exe agent"
     win_copy:
      src: zabbix_agent2.exe
      dest: C:\sp0066\Downloads\

   - name: "Copy Configuration Files"
     win_copy:
      src: zabbix_agent2.win.conf
      dest: C:\sp0066\Downloads\

   - name: Run a command under PowerShell
     win_shell: C:\sp0066\Downloads\zabbix_agent2.exe --install

   - name: "Restart the Zabbix Service"
     win_service:
       name: Zabbix Agent 2
       state: started