---
- name: "*** ClamAV install ***"
  hosts: testslaves
  become: true
  become_user: root
  gather_facts: true

  tasks:
    - name: Get service facts
      service_facts:

    - name: "Check Rhel-7 Clamav Service Status"
      debug:
        var: ansible_facts.services["clamd@scan.service"]
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

    - name: "Check Rhel-6 Clamav Service Status"
      debug:
        var: ansible_facts.services["clamd.service"]
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"