---
- hosts: localhost
  become: yes
  become_user: root
  gather_facts: false

  tasks:
    - name: "Comment out hosts"
      lineinfile:
        path: data.yml.j2
        # search_string: 'hosts: ["10.100.32.39:5044"]'
        regexp: 'hosts:'
        line: '  hosts: ["p1apelk306:5044", "p1apelk307:5044"]'


    - name: "Add details about Host and Load Balancer"
      lineinfile:
        path: data.yml.j2
        insertbefore: 'newvalue'
        line: 'loadbalance: true'