---
- hosts: localhost
  gather_facts: no
  become: yes
  become_user: root

  tasks:
  - name: "Comment Ciphers Line"
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^Ciphers'
      line: '# Ciphers 3des-cbc,aes128-cbc,aes128-ctr,aes192-ctr,aes256-ctr'

  - name: "Upgrade SSH configuration"
    lineinfile:
      path: /etc/ssh/sshd_config
      line: 'Ciphers aes128-cbc,aes192-ctr,aes256-ctr'
      insertafter: '# Ciphers 3des-cbc,aes128-cbc,aes128-ctr,aes192-ctr,aes256-ctr'

  - name: "Restart SSH"
    service:
      name: sshd
      state: restarted